// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Data;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250616151127_AddDoktorSeed")]
    partial class AddDoktorSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebAPI.Models.Domain.Doktor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Doktor");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-11d3-9a0c-0305e82c3301"),
                            Ad = "Ali",
                            Email = "ali@example.com",
                            Soyad = "Yılmaz"
                        },
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-11d3-9a0c-0305e82c8888"),
                            Ad = "Ayşe",
                            Email = "ayse@example.com",
                            Soyad = "Kaya"
                        },
                        new
                        {
                            Id = new Guid("3f2504e0-abcd-11d3-9a0c-0305e82c1111"),
                            Ad = "Mehmet",
                            Email = "mehmet@example.com",
                            Soyad = "Demir"
                        },
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-11d3-9a0c-0305e82c5555"),
                            Ad = "Fatma",
                            Email = "fatma@example.com",
                            Soyad = "Çelik"
                        });
                });

            modelBuilder.Entity("WebAPI.Models.Domain.Etiket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("EtiketAd")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Etiket");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EtiketAd = "A"
                        },
                        new
                        {
                            Id = 2,
                            EtiketAd = "B"
                        },
                        new
                        {
                            Id = 3,
                            EtiketAd = "C"
                        });
                });

            modelBuilder.Entity("WebAPI.Models.Domain.Fotograf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FotografPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Fotograf");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FotografPath = "cat.1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            FotografPath = "cat.2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            FotografPath = "cat.3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            FotografPath = "cat.4.jpg"
                        });
                });

            modelBuilder.Entity("WebAPI.Models.Domain.FotografEtiket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<Guid>("DoktorId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("EtiketId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EtiketTarihi")
                        .HasColumnType("date");

                    b.Property<int>("FotografId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoktorId");

                    b.HasIndex("EtiketId");

                    b.HasIndex("FotografId");

                    b.ToTable("FotografEtiket");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DoktorId = new Guid("3f2504e0-4f89-11d3-9a0c-0305e82c3301"),
                            EtiketId = 1,
                            EtiketTarihi = new DateOnly(2028, 5, 21),
                            FotografId = 1
                        },
                        new
                        {
                            Id = 2,
                            DoktorId = new Guid("3f2504e0-4f89-11d3-9a0c-0305e82c8888"),
                            EtiketId = 2,
                            EtiketTarihi = new DateOnly(2022, 2, 5),
                            FotografId = 1
                        },
                        new
                        {
                            Id = 3,
                            DoktorId = new Guid("3f2504e0-abcd-11d3-9a0c-0305e82c1111"),
                            EtiketId = 2,
                            EtiketTarihi = new DateOnly(2021, 1, 2),
                            FotografId = 2
                        },
                        new
                        {
                            Id = 4,
                            DoktorId = new Guid("3f2504e0-4f89-11d3-9a0c-0305e82c5555"),
                            EtiketId = 3,
                            EtiketTarihi = new DateOnly(2023, 3, 8),
                            FotografId = 2
                        });
                });

            modelBuilder.Entity("WebAPI.Models.Domain.FotografEtiket", b =>
                {
                    b.HasOne("WebAPI.Models.Domain.Doktor", "Doktor")
                        .WithMany("FotografEtiketleri")
                        .HasForeignKey("DoktorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.Models.Domain.Etiket", "Etiket")
                        .WithMany("FotografEtiketleri")
                        .HasForeignKey("EtiketId");

                    b.HasOne("WebAPI.Models.Domain.Fotograf", "Fotograf")
                        .WithMany("FotografEtiketleri")
                        .HasForeignKey("FotografId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doktor");

                    b.Navigation("Etiket");

                    b.Navigation("Fotograf");
                });

            modelBuilder.Entity("WebAPI.Models.Domain.Doktor", b =>
                {
                    b.Navigation("FotografEtiketleri");
                });

            modelBuilder.Entity("WebAPI.Models.Domain.Etiket", b =>
                {
                    b.Navigation("FotografEtiketleri");
                });

            modelBuilder.Entity("WebAPI.Models.Domain.Fotograf", b =>
                {
                    b.Navigation("FotografEtiketleri");
                });
#pragma warning restore 612, 618
        }
    }
}
