// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Data;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250613160140_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebAPI.Models.Domain.Doktor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Doktor");
                });

            modelBuilder.Entity("WebAPI.Models.Domain.Etiket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("EtiketAd")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Etiket");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EtiketAd = "A"
                        },
                        new
                        {
                            Id = 2,
                            EtiketAd = "B"
                        },
                        new
                        {
                            Id = 3,
                            EtiketAd = "C"
                        });
                });

            modelBuilder.Entity("WebAPI.Models.Domain.Fotograf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FotografPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Fotograf");
                });

            modelBuilder.Entity("WebAPI.Models.Domain.FotografEtiket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DoktorId")
                        .HasColumnType("int");

                    b.Property<int?>("EtiketId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EtiketTarihi")
                        .HasColumnType("date");

                    b.Property<int>("FotografId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoktorId");

                    b.HasIndex("EtiketId");

                    b.HasIndex("FotografId");

                    b.ToTable("FotografEtiket");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DoktorId = 1,
                            EtiketId = 1,
                            EtiketTarihi = new DateOnly(2028, 5, 21),
                            FotografId = 1
                        },
                        new
                        {
                            Id = 2,
                            DoktorId = 1,
                            EtiketId = 2,
                            EtiketTarihi = new DateOnly(2022, 2, 5),
                            FotografId = 1
                        },
                        new
                        {
                            Id = 3,
                            DoktorId = 2,
                            EtiketId = 2,
                            EtiketTarihi = new DateOnly(2021, 1, 2),
                            FotografId = 2
                        },
                        new
                        {
                            Id = 4,
                            DoktorId = 2,
                            EtiketId = 3,
                            EtiketTarihi = new DateOnly(2023, 3, 8),
                            FotografId = 2
                        });
                });

            modelBuilder.Entity("WebAPI.Models.Domain.FotografEtiket", b =>
                {
                    b.HasOne("WebAPI.Models.Domain.Doktor", "Doktor")
                        .WithMany("FotografEtiketleri")
                        .HasForeignKey("DoktorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.Models.Domain.Etiket", "Etiket")
                        .WithMany("FotografEtiketleri")
                        .HasForeignKey("EtiketId");

                    b.HasOne("WebAPI.Models.Domain.Fotograf", "Fotograf")
                        .WithMany("FotografEtiketleri")
                        .HasForeignKey("FotografId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doktor");

                    b.Navigation("Etiket");

                    b.Navigation("Fotograf");
                });

            modelBuilder.Entity("WebAPI.Models.Domain.Doktor", b =>
                {
                    b.Navigation("FotografEtiketleri");
                });

            modelBuilder.Entity("WebAPI.Models.Domain.Etiket", b =>
                {
                    b.Navigation("FotografEtiketleri");
                });

            modelBuilder.Entity("WebAPI.Models.Domain.Fotograf", b =>
                {
                    b.Navigation("FotografEtiketleri");
                });
#pragma warning restore 612, 618
        }
    }
}
